# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1111():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1111(self):
    self.driver.get("https://www.avtodispetcher.ru/distance/?from=%D0%A2%D1%83%D0%BB%D0%B0&to=%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&v=&vt=car&rm=110&rp=90&rs=60&ru=40&fc=9&fp=46&ov=&atn=&aup=&atr=&afd=&ab=&acb=")
    self.driver.set_window_size(1144, 882)
    time.sleep(2)
    target =  self.driver.find_element(By.CSS_SELECTOR, ".anchor")
    target.location_once_scrolled_into_view
    self.driver.find_element(By.CSS_SELECTOR, ".anchor").click()
    self.driver.find_element(By.NAME, "v").send_keys("Великий Новгород")
    target =  self.driver.find_element(By.CSS_SELECTOR, ".submit_button > input")
    target.location_once_scrolled_into_view
    self.driver.find_element(By.CSS_SELECTOR, ".submit_button > input").click()
    
    self.driver.execute_script("window.scrollTo(0,300)")
    time.sleep(20)
    self.driver.find_element(By.CSS_SELECTOR, "p > input:nth-child(4)").click()
  
